services:
  - type: web
    name: recommendation-engine-backend
    env: python
    plan: free
    buildCommand: pip install torch --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt
    startCommand: uvicorn src.serving.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: recommendation-engine-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: recommendation-engine-redis
          property: port

  - type: web
    name: recommendation-engine-frontend
    env: static
    plan: free
    publishPath: ./frontend

  - type: redis
    name: recommendation-engine-redis
    plan: free
    ipAllowList: []
